# Generated by Django 4.0.8 on 2022-12-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='libros/', verbose_name='Imagen'),
        ),
    ]
